# Assignment No 3
### 41363 Rushikesh Chaudhari
## Batch R3
## Given a bank customer, build a neural network-based classifier that can determine whether they will leave or not in the next 6 months.
## Dataset Description: The case study is from an open-source dataset from Kaggle. The dataset contains 10,000 sample points with 14 distinct features such as CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance, etc.
## Perform following steps:
## 1.	Read the dataset.
## 2.	Distinguish the feature and target set and divide the data set into training and test sets.
## 3.	Normalize the train and test data.
## 4.	Initialize and build the model. Identify the points of improvement and implement the same.
## Print the accuracy score and confusion matrix


In [1]:
import numpy as np # linear algebra
import pandas as pd 

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df.shape

(10000, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
x = df.iloc[:,3:-1].values
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
y = df.iloc[:,-1].values
print(y)

[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [8]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7474
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4605 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4433 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4339 - accuracy: 0.7962
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4278 - accuracy: 0.8056
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4231 - accuracy: 0.8166
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4186 - accuracy: 0.8213
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4143 - accuracy: 0.8246
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4110 - accuracy: 0.8274
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4074 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3362 - accuracy: 0.8637
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 0.8660
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8652
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8646
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3361 - accuracy: 0.8664
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3359 - accuracy: 0.8637
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3361 - accuracy: 0.8649
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 0.8654
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3354 - accuracy: 0.8646
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3357 - accuracy: 

In [15]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 197  208]]


0.862